//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreThanBefore.Models.SellerCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SellerCenterDbContext : DbContext
    {
        public SellerCenterDbContext()
            : base("name=SellerCenterDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ecombase_currency> tbl_ecombase_currency { get; set; }
        public virtual DbSet<tbl_ecombase_produnit> tbl_ecombase_produnit { get; set; }
        public virtual DbSet<tbl_products> tbl_products { get; set; }
        public virtual DbSet<tbl_sc_users> tbl_sc_users { get; set; }
        public virtual DbSet<tbl_sc_acl> tbl_sc_acl { get; set; }
        public virtual DbSet<tbl_sc_acl_roleassign> tbl_sc_acl_roleassign { get; set; }
        public virtual DbSet<tbl_sc_roles> tbl_sc_roles { get; set; }
        public virtual DbSet<tbl_sc_roles_userassign> tbl_sc_roles_userassign { get; set; }
    }
}
