//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreThanBefore.Models.SellerCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sc_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_sc_users()
        {
            this.tbl_products = new HashSet<tbl_products>();
            this.tbl_sc_acl = new HashSet<tbl_sc_acl>();
            this.tbl_sc_acl_roleassign = new HashSet<tbl_sc_acl_roleassign>();
            this.tbl_sc_roles = new HashSet<tbl_sc_roles>();
            this.tbl_sc_roles_userassign = new HashSet<tbl_sc_roles_userassign>();
            this.tbl_sc_roles_userassign1 = new HashSet<tbl_sc_roles_userassign>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string hashedPassword { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string emailAddress { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_products> tbl_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sc_acl> tbl_sc_acl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sc_acl_roleassign> tbl_sc_acl_roleassign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sc_roles> tbl_sc_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sc_roles_userassign> tbl_sc_roles_userassign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sc_roles_userassign> tbl_sc_roles_userassign1 { get; set; }
    }
}
