//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreThanBefore.Models.SellerCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sc_acl_roleassign
    {
        public int id { get; set; }
        public int acl { get; set; }
        public int role { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual tbl_sc_acl tbl_sc_acl { get; set; }
        public virtual tbl_sc_roles tbl_sc_roles { get; set; }
        public virtual tbl_sc_users tbl_sc_users { get; set; }
    }
}
