//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreThanBefore.Models.SellerCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        public int id { get; set; }
        public string prodName { get; set; }
        public string prodDesc { get; set; }
        public int prodUnit { get; set; }
        public Nullable<decimal> prodPricePerUnit { get; set; }
        public int prodCurrency { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual tbl_ecombase_currency tbl_ecombase_currency { get; set; }
        public virtual tbl_ecombase_produnit tbl_ecombase_produnit { get; set; }
        public virtual tbl_sc_users tbl_sc_users { get; set; }
    }
}
